handle: stripe
isFrontendEnabled: true
name: Stripe
paymentType: purchase
settings:
  apiKey: $STRIPE_SECRET_KEY
  publishableKey: $STRIPE_PUBLISHABLE_KEY
  sendReceiptEmail: '1'
  signingSecret: whsec_tweuWeI1SwgqA9r34YCYknTwS6up4pMq
sortOrder: 99
type: craft\commerce\stripe\gateways\PaymentIntents
