fieldLayouts:
  4b3c7ece-9fce-4b78-ac55-c064173b5210:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            warning: null
            width: 100
          -
            fieldUid: 0c65e01e-98b0-4db1-ada2-e3708f2dad9a # Podcast Art Optimize
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f1f3895-7bf1-4729-800b-82700ff99637 # Two Coins Team Optimize
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4b9e06a3-881b-49da-9c61-a1719a6112f3 # Story Images Optimize
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: podcast
hasUrls: true
name: Podcast
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: simple-charity
  bucketSelectionMode: choose
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: ''
  expires: '30 days'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: us-east-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: site/podcast
sortOrder: 9
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
