fieldLayouts:
  f515f366-0751-4227-b41b-d2502de5f614:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: practice
hasUrls: true
name: Practice
settings:
  addSubfolderToRootUrl: true
  autoFocalPoint: ''
  bucket: simple-charity
  bucketSelectionMode: choose
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: ''
  expires: '30 days'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: us-east-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: site/practice
sortOrder: 7
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
