fieldLayouts:
  637818a4-369e-4a61-9061-d070fbbfb159:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: 4b9e06a3-881b-49da-9c61-a1719a6112f3 # Story Images Optimize
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f61a4ddd-c861-4510-bfb4-2f6252b46159 # Image Caption
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: stories
hasUrls: true
name: Stories
settings:
  addSubfolderToRootUrl: true
  autoFocalPoint: ''
  bucket: simple-charity
  bucketSelectionMode: choose
  cfDistributionId: $CLOUDFRONT_DISTRIBUTION_ID
  cfPrefix: ''
  expires: '30 days'
  keyId: $S3_KEY_ID
  makeUploadsPublic: ''
  region: us-east-2
  secret: $S3_SECRET
  storageClass: ''
  subfolder: site/stories
sortOrder: 5
titleTranslationKeyFormat: null
titleTranslationMethod: site
type: craft\awss3\Volume
url: $CLOUDFRONT_URL
