defaultPlacement: end
enableVersioning: true
handle: donate
name: Donate
propagationMethod: all
siteSettings:
  972e83d1-5fbc-4d0f-b1f1-674d47402fbd: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: charities/index
    uriFormat: charities
type: single
