defaultPlacement: end
enableVersioning: true
handle: internship
name: Internship
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  972e83d1-5fbc-4d0f-b1f1-674d47402fbd: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: internship/index
    uriFormat: internship
type: single
