defaultPlacement: end
enableVersioning: false
handle: verses
name: Verses
propagationMethod: all
siteSettings:
  972e83d1-5fbc-4d0f-b1f1-674d47402fbd: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: verses/_entry
    uriFormat: 'verses/{slug}'
type: channel
