field: 6b4827de-4f95-4753-a795-7df4cf10ae21 # Footer Red Buttons
fieldLayouts:
  1a14877a-3d3e-4e60-ab5b-490dc0d6f2ee:
    tabs:
      -
        elements:
          -
            fieldUid: fe3762fb-c042-4a4c-98fd-92b834600bea # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3cf44beb-7d3a-4341-9fc0-b1f0a6794d39 # Button Internal Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6be23140-da04-425c-9a62-dc03b011978c # Button External Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3cf44beb-7d3a-4341-9fc0-b1f0a6794d39: # Button Internal Reference
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonInternalReference
    instructions: 'Don''t fill this out if there is an external reference. '
    name: 'Button Internal Reference'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  6be23140-da04-425c-9a62-dc03b011978c: # Button External Reference
    columnSuffix: yrupcnxi
    contentColumnType: text
    fieldGroup: null
    handle: buttonExternalReference
    instructions: 'Don''t fill this out if there is an internal reference. '
    name: 'Button External Reference'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fe3762fb-c042-4a4c-98fd-92b834600bea: # Button Text
    columnSuffix: uitfwruk
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 1
