field: 31c69751-2869-46a7-8948-2ebeaba8d0d4 # Generic Button
fieldLayouts:
  bafa43cc-04b9-44cf-bf62-0c979d102320:
    tabs:
      -
        elements:
          -
            fieldUid: b4ce1ebd-62b7-49f1-98c0-3c9b74551163 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fd6e3b6d-7d3d-4ff1-8f5f-4c1c6807f60f # Button Internal Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6609447-534e-4790-93ed-78f3126b283a # Button External Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  b4ce1ebd-62b7-49f1-98c0-3c9b74551163: # Button Text
    columnSuffix: kvctsjgt
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c6609447-534e-4790-93ed-78f3126b283a: # Button External Reference
    columnSuffix: butllbjz
    contentColumnType: text
    fieldGroup: null
    handle: buttonExternalReference
    instructions: 'Fill this out only if there is not an internal reference. '
    name: 'Button External Reference'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  fd6e3b6d-7d3d-4ff1-8f5f-4c1c6807f60f: # Button Internal Reference
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonInternalReference
    instructions: ''
    name: 'Button Internal Reference'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: button
name: Button
sortOrder: 1
