field: aac43d31-1173-4e0f-a26f-b7fb6a683b20 # Banner 6 Button
fieldLayouts:
  c4014254-b7e8-409b-bf34-a062118ba924:
    tabs:
      -
        elements:
          -
            fieldUid: 2214864f-655a-48c1-93cc-1f3c1da267e3 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 182e1836-75d2-4cd5-ac90-64d89a75da20 # Button Internal Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d744994f-f96c-4477-adfa-7611841828f4 # Button External Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  182e1836-75d2-4cd5-ac90-64d89a75da20: # Button Internal Reference
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonInternalReference
    instructions: ''
    name: 'Button Internal Reference'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: ''
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  2214864f-655a-48c1-93cc-1f3c1da267e3: # Button Text
    columnSuffix: ymwfowiy
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  d744994f-f96c-4477-adfa-7611841828f4: # Button External Reference
    columnSuffix: ilzijxve
    contentColumnType: text
    fieldGroup: null
    handle: buttonExternalReference
    instructions: 'Fill this out only if there is no internal reference. '
    name: 'Button External Reference'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: button
name: Button
sortOrder: 1
