field: b250d29c-4a5c-4fba-b92e-58a95fc43979 # Internship Cards
fieldLayouts:
  8b8f0f0b-d7a0-43ca-ad4e-d5d01d322e55:
    tabs:
      -
        elements:
          -
            fieldUid: 85a7ad98-8a42-4758-aed2-e663d86f0e91 # Card Title Line 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 511911d0-c9d8-4422-9c29-0a544f4aac56 # Card Title Line 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 017a6d9a-8363-4430-a835-d4b46fbfad7e # Card Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 5c103e86-4a79-4df8-bbf0-f3f70263f05c # Card Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  5c103e86-4a79-4df8-bbf0-f3f70263f05c: # Card Color
    columnSuffix: ltystmgc
    contentColumnType: string
    fieldGroup: null
    handle: cardColor
    instructions: ''
    name: 'Card Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  017a6d9a-8363-4430-a835-d4b46fbfad7e: # Card Text
    columnSuffix: mueyntgt
    contentColumnType: text
    fieldGroup: null
    handle: cardText
    instructions: ''
    name: 'Card Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  85a7ad98-8a42-4758-aed2-e663d86f0e91: # Card Title Line 1
    columnSuffix: kwhywugl
    contentColumnType: text
    fieldGroup: null
    handle: cardTitleLine1
    instructions: ''
    name: 'Card Title Line 1'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  511911d0-c9d8-4422-9c29-0a544f4aac56: # Card Title Line 2
    columnSuffix: xuhkrlei
    contentColumnType: text
    fieldGroup: null
    handle: cardTitleLine2
    instructions: ''
    name: 'Card Title Line 2'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: card
name: Card
sortOrder: 1
