field: 08d66bf8-3c98-44fc-bce4-5eeccc3262f0 # Chapters Cards
fieldLayouts:
  98228d11-506e-447a-976e-c82030a32763:
    tabs:
      -
        elements:
          -
            fieldUid: c11dbccc-6db1-49f7-bac9-d29548d3dd79 # Theme Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 96a3a2bf-3ba6-4971-bdac-424836af4fd6 # Card Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ca540986-d511-438a-b232-0de70f87e68c # Card Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 749345ed-14a2-4cd9-a226-dbcee39cda0b # Card Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c8b0b5fc-f91a-4e26-831d-8d94ac4d9acd # Card Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: de54fd56-d7d3-4f67-8e0d-8a12f4d573a0 # Card Button Internal Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ac574ed6-29fe-4d5a-856f-0d80713a70fa # Card Button External Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  96a3a2bf-3ba6-4971-bdac-424836af4fd6: # Card Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardTitle
    instructions: ''
    name: 'Card Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  749345ed-14a2-4cd9-a226-dbcee39cda0b: # Card Icon
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardIcon
    instructions: ''
    name: 'Card Icon'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ac574ed6-29fe-4d5a-856f-0d80713a70fa: # Card Button External Reference
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardButtonExternalReference
    instructions: 'Fill this out only is there is no internal reference. '
    name: 'Card Button External Reference'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c8b0b5fc-f91a-4e26-831d-8d94ac4d9acd: # Card Button Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardButtonText
    instructions: ''
    name: 'Card Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  c11dbccc-6db1-49f7-bac9-d29548d3dd79: # Theme Color
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: themeColor
    instructions: ''
    name: 'Theme Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Mint
            -
              - value
              - mint
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Peach
            -
              - value
              - peach
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Canary
            -
              - value
              - canary
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Zeal
            -
              - value
              - zeal
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Quartz
            -
              - value
              - quartz
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Dusk
            -
              - value
              - dusk
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  ca540986-d511-438a-b232-0de70f87e68c: # Card Description
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: cardDescription
    instructions: ''
    name: 'Card Description'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Paragraphs.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  de54fd56-d7d3-4f67-8e0d-8a12f4d573a0: # Card Button Internal Reference
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: cardButtonInternalReference
    instructions: ''
    name: 'Card Button Internal Reference'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
handle: card
name: Card
sortOrder: 1
