field: 4edd14c6-083e-49b7-9ec9-fc5576a70d24 # Philosophy Descriptions
fieldLayouts:
  92bf8502-9225-4996-b1bd-12df94c821bf:
    tabs:
      -
        elements:
          -
            fieldUid: aea75f95-a95c-48dc-a688-d8c7e0693776 # Block Header Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8e4389b1-a62a-46c4-a206-6e34d74ff728 # Block Body Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  8e4389b1-a62a-46c4-a206-6e34d74ff728: # Block Body Text
    columnSuffix: eymadbym
    contentColumnType: text
    fieldGroup: null
    handle: blockBodyText
    instructions: ''
    name: 'Block Body Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  aea75f95-a95c-48dc-a688-d8c7e0693776: # Block Header Text
    columnSuffix: rctunobt
    contentColumnType: text
    fieldGroup: null
    handle: blockHeaderText
    instructions: ''
    name: 'Block Header Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: descriptionBlock
name: 'Description Block'
sortOrder: 1
