field: 94080954-ce37-4713-bdbf-59590c7cf19a # Charity Type Descriptions
fieldLayouts:
  42a5df42-09d0-43ac-9369-290db5933460:
    tabs:
      -
        elements:
          -
            fieldUid: efdc869f-a789-402b-a6fa-3e560a7f5f68 # Description Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  efdc869f-a789-402b-a6fa-3e560a7f5f68: # Description Text
    columnSuffix: axdmjuyg
    contentColumnType: text
    fieldGroup: null
    handle: descriptionText
    instructions: ''
    name: 'Description Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: description
name: Description
sortOrder: 1
