field: 7909aed5-381b-437e-bf82-394caf136412 # Compliance Documents
fieldLayouts:
  1825f261-12e5-4ad6-942b-075dfc723dfc:
    tabs:
      -
        elements:
          -
            fieldUid: baa044fa-a14b-4fd1-b298-40c90408c4f5 # Document Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 35aff1de-27ed-4f68-ba82-fa39cbf4516e # Document Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  35aff1de-27ed-4f68-ba82-fa39cbf4516e: # Document Link
    columnSuffix: eckcyijc
    contentColumnType: text
    fieldGroup: null
    handle: documentLink
    instructions: ''
    name: 'Document Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  baa044fa-a14b-4fd1-b298-40c90408c4f5: # Document Name
    columnSuffix: touwfioa
    contentColumnType: text
    fieldGroup: null
    handle: documentName
    instructions: ''
    name: 'Document Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: document
name: Document
sortOrder: 1
