field: 47a5e597-de28-4a21-bd8e-7d6849507248 # Countries of Operation
fieldLayouts:
  2b4d63d3-3cae-44dd-a232-d20811553a2e:
    tabs:
      -
        elements:
          -
            fieldUid: 28ec04f3-9b85-4bce-82d5-3e611c99266c # Countries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  28ec04f3-9b85-4bce-82d5-3e611c99266c: # Countries
    columnSuffix: courmwla
    contentColumnType: text
    fieldGroup: null
    handle: countries
    instructions: 'Put each country in this region in which the partner operates, separated by commas. '
    name: Countries
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: europeCentralAsia
name: 'Europe & Central Asia'
sortOrder: 2
