field: 4a8b9b05-085d-4268-ba7c-c6981afdf494 # Podcast Externals
fieldLayouts:
  c837c5f0-0410-4a62-8c2f-a2ea36315b16:
    tabs:
      -
        elements:
          -
            fieldUid: b7755107-5b9c-4c16-9252-ab2617412513 # External Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a773b31a-744d-47d2-b844-6e31a966ea18 # External Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  a773b31a-744d-47d2-b844-6e31a966ea18: # External Link
    columnSuffix: sbqyprkt
    contentColumnType: text
    fieldGroup: null
    handle: externalLink
    instructions: ''
    name: 'External Link'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  b7755107-5b9c-4c16-9252-ab2617412513: # External Name
    columnSuffix: thybzuow
    contentColumnType: text
    fieldGroup: null
    handle: externalName
    instructions: ''
    name: 'External Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: external
name: External
sortOrder: 1
