field: 9fda4d0f-88f7-4fd5-9c19-262099d2666f # Podcast Credits
fieldLayouts:
  60d01b94-ac72-4449-9408-cdb3cd48bada:
    tabs:
      -
        elements:
          -
            fieldUid: 5a177aa1-a238-44c2-a6fb-7f62483aa7aa # Credit Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 3bfa9a72-d3b5-4b7a-be32-215d6d0e1da9 # Credit Contents
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  3bfa9a72-d3b5-4b7a-be32-215d6d0e1da9: # Credit Contents
    columnSuffix: xpmpxkaq
    contentColumnType: text
    fieldGroup: null
    handle: creditContents
    instructions: ''
    name: 'Credit Contents'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  5a177aa1-a238-44c2-a6fb-7f62483aa7aa: # Credit Header
    columnSuffix: yxddftll
    contentColumnType: text
    fieldGroup: null
    handle: creditHeader
    instructions: ''
    name: 'Credit Header'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: hiddenCredit
name: 'Hidden Credit'
sortOrder: 2
