field: 9d38787a-2df0-4447-8a8d-2ad0dbfaf9fe # Interns
fieldLayouts:
  ba16269a-d0a1-4349-b740-ae4bad3ea45f:
    tabs:
      -
        elements:
          -
            fieldUid: cfb0632d-25e2-41d9-85de-8dd0459f75f4 # Class year
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21326ee3-1880-4180-b8af-aec1bcd0d24f # Class Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b262edd9-8091-48a3-9dc9-77db75491dca # Class Names
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  21326ee3-1880-4180-b8af-aec1bcd0d24f: # Class Photo
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: classPhoto
    instructions: ''
    name: 'Class Photo'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  b262edd9-8091-48a3-9dc9-77db75491dca: # Class Names
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: classNames
    instructions: ''
    name: 'Class Names'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ParagraphsBeliefs.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  cfb0632d-25e2-41d9-85de-8dd0459f75f4: # Class year
    columnSuffix: null
    contentColumnType: string(16)
    fieldGroup: null
    handle: classYear
    instructions: ''
    name: 'Class year'
    searchable: false
    settings:
      byteLimit: null
      charLimit: 4
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: internClass
name: 'Intern Class'
sortOrder: 1
