field: e73f75de-459c-405a-b05e-3e6c9a95f31b # Stories Main Block
fieldLayouts:
  4bd78644-10f8-4f1b-ace4-3d124c1d5328:
    tabs:
      -
        elements:
          -
            fieldUid: 09df7167-6b69-4826-930b-2ab1f9245a8f # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  09df7167-6b69-4826-930b-2ab1f9245a8f: # Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: 'Enter the text for this block.'
    name: Text
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Paragraphs.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: largeText
name: 'Large Text'
sortOrder: 1
