field: 96aa5e33-5392-4f29-84b8-97fea9f6d69d # Partner Dropdowns
fieldLayouts:
  949fd9aa-5720-4afc-86d8-79b8dda3e5b8:
    tabs:
      -
        elements:
          -
            fieldUid: df0dd3e8-515f-4f18-bd97-1899cfa71f76 # Dropdown Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  df0dd3e8-515f-4f18-bd97-1899cfa71f76: # Dropdown Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: dropdownTitle
    instructions: ''
    name: 'Dropdown Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: mapDropdown
name: 'Map Dropdown'
sortOrder: 2
