field: 47a5e597-de28-4a21-bd8e-7d6849507248 # Countries of Operation
fieldLayouts:
  35042f1b-4f98-42d8-a7bc-ad02bd6b542b:
    tabs:
      -
        elements:
          -
            fieldUid: cd91f2cf-1a0f-4de4-a251-d24a7565b1f6 # Countries
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  cd91f2cf-1a0f-4de4-a251-d24a7565b1f6: # Countries
    columnSuffix: vovvkelx
    contentColumnType: text
    fieldGroup: null
    handle: countries
    instructions: 'Put each country in this region in which the partner operates, separated by commas. '
    name: Countries
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: northAmerica
name: 'North America'
sortOrder: 5
