field: 2e9028ad-d3e4-4f65-ad46-1432e2aebf6c # Philosophy Images Crop
fieldLayouts:
  7325a129-b21d-4424-8866-25abeb280013:
    tabs:
      -
        elements:
          -
            fieldUid: 49266c81-7658-4038-b516-a89e6ae4e869 # Phil Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  49266c81-7658-4038-b516-a89e6ae4e869: # Phil Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: philImage
    instructions: ''
    name: 'Phil Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: philImage
name: 'Phil Image'
sortOrder: 1
