field: 4e4a3721-3a3f-40e3-860a-ba1da4738a40 # Podcast External Buttons
fieldLayouts:
  de0bfa46-4b5d-4ce6-ae9f-b0dec7180a9a:
    tabs:
      -
        elements:
          -
            fieldUid: 81bce76b-b274-46c4-9fae-74182379b6e2 # External Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0e595d14-742b-4de7-9fc6-42365855aee2 # External URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0e595d14-742b-4de7-9fc6-42365855aee2: # External URL
    columnSuffix: lnibrvsg
    contentColumnType: text
    fieldGroup: null
    handle: externalUrl
    instructions: ''
    name: 'External URL'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  81bce76b-b274-46c4-9fae-74182379b6e2: # External Name
    columnSuffix: iaylcnbh
    contentColumnType: text
    fieldGroup: null
    handle: externalName
    instructions: ''
    name: 'External Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: podcastExternal
name: 'Podcast External'
sortOrder: 1
