field: 22719c53-1950-419d-9fcf-6889e131a46e # Page
fieldLayouts:
  00b1f8e2-fb09-4bcb-a5fe-1c27342f523c:
    tabs:
      -
        elements:
          -
            fieldUid: 2188e671-8d1a-4e08-9aff-3c4076303ef1 # Paragraphs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2188e671-8d1a-4e08-9aff-3c4076303ef1: # Paragraphs
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: paragraphs
    instructions: ''
    name: Paragraphs
    searchable: false
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ParagraphsBeliefs.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: smallParagraphs
name: 'Small Paragraphs'
sortOrder: 4
