field: 42cd3015-be61-46b7-8573-61ffe6fe3034 # Stories Hidden Block
fieldLayouts:
  463aa5bf-25a0-467f-acdc-0136546a11d1:
    tabs:
      -
        elements:
          -
            fieldUid: 85740b79-0aac-41af-98f9-45e3fa4036f3 # Small Image
            instructions: null
            label: null
            required: '0'
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  85740b79-0aac-41af-98f9-45e3fa4036f3: # Small Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: smallImage
    instructions: ''
    name: 'Small Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: true
      singleUploadLocationSource: 'volume:8dc0f459-1205-4e5b-b0ef-c44e4cea4c5d' # Stories
      singleUploadLocationSubpath: '{owner.slug}'
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: smallImage
name: 'Small Image'
sortOrder: 3
