field: 9c051f34-07ac-45aa-be8b-5b68c079a7f7 # Table Data
fieldLayouts:
  abb81ba8-265d-45f6-b455-8a554a8b67ce:
    tabs:
      -
        elements:
          -
            fieldUid: d4c1d637-d996-4e25-a33b-c460f1cefb7c # Stat 2021
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  d4c1d637-d996-4e25-a33b-c460f1cefb7c: # Stat 2021
    columnSuffix: dvglxkij
    contentColumnType: text
    fieldGroup: null
    handle: stat2021
    instructions: ''
    name: 'Stat 2021'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stat2021
name: 'Stat 2021'
sortOrder: 4
