field: 9c051f34-07ac-45aa-be8b-5b68c079a7f7 # Table Data
fieldLayouts:
  f407d30b-76de-4f2e-8769-178c53883bb5:
    tabs:
      -
        elements:
          -
            fieldUid: 1ba99be8-6267-40cf-a5e8-6e9dc5b5d264 # Stat 2019
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  1ba99be8-6267-40cf-a5e8-6e9dc5b5d264: # Stat 2019
    columnSuffix: yjkvrrtv
    contentColumnType: text
    fieldGroup: null
    handle: stat2019
    instructions: ''
    name: 'Stat 2019'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stat2019
name: 'Stat 2019'
sortOrder: 2
