field: 9b2e1c42-74f9-44d1-999b-06178679243e # Core Stats
fieldLayouts:
  3e7664dc-2d40-46c9-979a-78545250de9f:
    tabs:
      -
        elements:
          -
            fieldUid: 08978650-1446-4ddf-b7c0-59a2cc216bb9 # Stat Name
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8185b768-43ae-4a3b-9a61-edd6c1fd25cf # Total Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6c26cd6d-1813-4f00-a368-174f87123749 # Year Breakdown
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 87439f8b-2414-47ce-8b44-a35d2c719d44 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e1989458-9b46-4582-b943-52b4b21537b9 # Button Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 593ca645-3540-406a-b8e9-7f62a5a41743 # Button Internal Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 975ac3bf-98a3-440f-93bf-d015b38015cc # Button External Reference
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  6c26cd6d-1813-4f00-a368-174f87123749: # Year Breakdown
    columnSuffix: zlymurzn
    contentColumnType: text
    fieldGroup: null
    handle: yearBreakdown
    instructions: ''
    name: 'Year Breakdown'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  593ca645-3540-406a-b8e9-7f62a5a41743: # Button Internal Reference
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttonInternalReference
    instructions: ''
    name: 'Button Internal Reference'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: false
      source: null
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  975ac3bf-98a3-440f-93bf-d015b38015cc: # Button External Reference
    columnSuffix: yqwzkpdg
    contentColumnType: text
    fieldGroup: null
    handle: buttonExternalReference
    instructions: 'Fill this out only if there is no internal reference.'
    name: 'Button External Reference'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  8185b768-43ae-4a3b-9a61-edd6c1fd25cf: # Total Amount
    columnSuffix: zsyppaaj
    contentColumnType: text
    fieldGroup: null
    handle: totalAmount
    instructions: ''
    name: 'Total Amount'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  87439f8b-2414-47ce-8b44-a35d2c719d44: # Background Color
    columnSuffix: crirrxpj
    contentColumnType: string
    fieldGroup: null
    handle: backgroundColor
    instructions: ''
    name: 'Background Color'
    searchable: false
    settings:
      optgroups: true
      options:
        -
          __assoc__:
            -
              - label
              - Blue
            -
              - value
              - blue
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Navy
            -
              - value
              - navy
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Red
            -
              - value
              - red
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Yellow
            -
              - value
              - yellow
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Green
            -
              - value
              - green
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Teal
            -
              - value
              - teal
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  08978650-1446-4ddf-b7c0-59a2cc216bb9: # Stat Name
    columnSuffix: kdtfrmwo
    contentColumnType: text
    fieldGroup: null
    handle: statName
    instructions: ''
    name: 'Stat Name'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e1989458-9b46-4582-b943-52b4b21537b9: # Button Text
    columnSuffix: ccccrayo
    contentColumnType: text
    fieldGroup: null
    handle: buttonText
    instructions: ''
    name: 'Button Text'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stat
name: Stat
sortOrder: 1
