field: 74284365-7a11-44ce-89c8-f0d2cdd8fc9d # Stats
fieldLayouts:
  edcaeccd-bd53-4919-af44-f7230b31a961:
    tabs:
      -
        elements:
          -
            fieldUid: 066d4391-417c-4728-9dbb-3ac06e26e59c # Amount
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 7ba86e8f-9c96-4a43-a163-1c01e03f3f54 # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  7ba86e8f-9c96-4a43-a163-1c01e03f3f54: # Description
    columnSuffix: vixrelkp
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: ''
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  066d4391-417c-4728-9dbb-3ac06e26e59c: # Amount
    columnSuffix: fyrpadgs
    contentColumnType: text
    fieldGroup: null
    handle: amount
    instructions: ''
    name: Amount
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: stat
name: Stat
sortOrder: 1
