field: 22719c53-1950-419d-9fcf-6889e131a46e # Page
fieldLayouts:
  b5142b71-aa5e-4087-aa8f-22cfe3b809dc:
    tabs:
      -
        elements:
          -
            fieldUid: 0f93676b-20d0-4cf7-b83e-58f339ce9e3a # Summary Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 2e19f39e-6e49-4e40-830a-df9ed9db43fd # Summary Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  0f93676b-20d0-4cf7-b83e-58f339ce9e3a: # Summary Text
    columnSuffix: dtbysnnk
    contentColumnType: text
    fieldGroup: null
    handle: summaryText
    instructions: ''
    name: 'Summary Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  2e19f39e-6e49-4e40-830a-df9ed9db43fd: # Summary Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: summaryImage
    instructions: ''
    name: 'Summary Image'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:7911f1e3-9cf4-4ddd-bc43-d9c4d701d47d' # Site
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: summaryBlock
name: 'Summary Block'
sortOrder: 7
