field: 96aa5e33-5392-4f29-84b8-97fea9f6d69d # Partner Dropdowns
fieldLayouts:
  54209bc7-3cf7-40f8-b0c0-62325b4a665e:
    tabs:
      -
        elements:
          -
            fieldUid: 52e0f93c-d81a-4364-bbcb-18927f6afdd4 # Dropdown Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  52e0f93c-d81a-4364-bbcb-18927f6afdd4: # Dropdown Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: dropdownTitle
    instructions: ''
    name: 'Dropdown Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: systemIconsDropdown
name: 'System Icons Dropdown'
sortOrder: 3
