field: 9c051f34-07ac-45aa-be8b-5b68c079a7f7 # Table Data
fieldLayouts:
  2995c47f-b892-4fc7-88b8-f3972e4c4128:
    tabs:
      -
        elements:
          -
            fieldUid: 250d3ba7-f022-4862-9180-ffc7f6c34eea # Row Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  250d3ba7-f022-4862-9180-ffc7f6c34eea: # Row Title
    columnSuffix: ngvzbxqe
    contentColumnType: text
    fieldGroup: null
    handle: rowTitle
    instructions: ''
    name: 'Row Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: tableEntry
name: 'Table Entry'
sortOrder: 1
