field: 96aa5e33-5392-4f29-84b8-97fea9f6d69d # Partner Dropdowns
fieldLayouts:
  98425834-d3f4-4f7a-8fa5-0321dcafb193:
    tabs:
      -
        elements:
          -
            fieldUid: ca0ab8ea-a3b8-4bb7-a0dd-4b975059ba37 # Dropdown Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 9596c2e0-a292-453a-b988-78bb9ed4a696 # Dropdown Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  9596c2e0-a292-453a-b988-78bb9ed4a696: # Dropdown Text
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: dropdownText
    instructions: ''
    name: 'Dropdown Text'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  ca0ab8ea-a3b8-4bb7-a0dd-4b975059ba37: # Dropdown Title
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: dropdownTitle
    instructions: ''
    name: 'Dropdown Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textDropdown
name: 'Text Dropdown'
sortOrder: 1
