field: 91538023-7219-4718-be32-9afb302568a7 # Generic Page Panels
fieldLayouts:
  01c8a8d6-ce4a-46c3-b522-e4aff50c44b1:
    tabs:
      -
        elements:
          -
            fieldUid: 2af57884-ba7e-4014-bcdf-93c6fb695a9a # Panel Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2af57884-ba7e-4014-bcdf-93c6fb695a9a: # Panel Title
    columnSuffix: xanghxut
    contentColumnType: text
    fieldGroup: null
    handle: panelTitle
    instructions: ''
    name: 'Panel Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: textImageButtonPanel
name: 'Text Image Button Panel'
sortOrder: 4
