columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: bigRedButton
instructions: ''
name: 'Big Red Button'
searchable: false
settings:
  contentTable: '{{%matrixcontent_bigredbutton}}'
  maxBlocks: '1'
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
