columnSuffix: null
contentColumnType: text
fieldGroup: 84e64693-a1cb-4ec1-a08e-4bded3602c99 # Blog
handle: blogTeaserText
instructions: ''
name: 'Blog Teaser Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
