columnSuffix: null
contentColumnType: string
fieldGroup: 84e64693-a1cb-4ec1-a08e-4bded3602c99 # Blog
handle: blogContent
instructions: ''
name: 'Blog Content'
searchable: true
settings:
  contentTable: '{{%matrixcontent_blogcontent}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
