columnSuffix: null
contentColumnType: text
fieldGroup: eefdc20f-9349-4de5-9eec-307948cedc5b # Start A Club
handle: clubMainText
instructions: ''
name: 'Club Main Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '3'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
