columnSuffix: null
contentColumnType: text
fieldGroup: eefdc20f-9349-4de5-9eec-307948cedc5b # Start A Club
handle: clubHeroText
instructions: ''
name: 'Club Hero Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
