columnSuffix: nnyabrfs
contentColumnType: boolean
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: completePage
instructions: ''
name: 'Complete Page'
searchable: false
settings:
  default: true
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
