columnSuffix: null
contentColumnType: text
fieldGroup: e44a1e2c-81bc-4b6c-bc42-306ce58de4a9 # Contact
handle: contactHeroText
instructions: ''
name: 'Contact Hero Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
