columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: currentCollegeChapters
instructions: 'This will not affect anything on the page. However, in the future we may use it. '
name: 'Current College Chapters'
searchable: false
settings:
  contentTable: '{{%matrixcontent_currentcollegechapters}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
