columnSuffix: null
contentColumnType: text
fieldGroup: 6366bfff-897e-466c-b6cb-63affba25b24 # Podcast
handle: episodeTitle
instructions: ''
name: 'Episode Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
