columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: genericButton2
instructions: ''
name: 'Generic Button 2'
searchable: false
settings:
  contentTable: '{{%matrixcontent_genericbutton2}}'
  maxBlocks: '1'
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
