columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: headerItems
instructions: ''
name: 'Header Items'
searchable: false
settings:
  contentTable: '{{%matrixcontent_headeritems}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
