columnSuffix: null
contentColumnType: text
fieldGroup: 601f52d6-827c-458a-ae29-ec5db8f8cd66 # ImageOptimize
handle: homepageImagesMobile
instructions: ''
name: 'Homepage Images Mobile'
searchable: true
settings:
  displayDominantColorPalette: '1'
  displayLazyLoadPlaceholderImages: '1'
  displayOptimizedImageVariants: '1'
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '5'
        -
          - aspectRatioY
          - '8'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '640'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '9'
        -
          - aspectRatioY
          - '16'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '300'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '9'
        -
          - aspectRatioY
          - '16'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '60'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
