columnSuffix: null
contentColumnType: text
fieldGroup: 641cdb99-2645-4b17-898a-343418e41a46 # Homepage
handle: homepageCoreBeliefsPromoText
instructions: ''
name: 'Homepage Core Beliefs Promo Text'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
