columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: imageCarousel
instructions: ''
name: 'Image Carousel'
searchable: false
settings:
  contentTable: '{{%matrixcontent_imagecarousel}}'
  maxBlocks: ''
  minBlocks: '1'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
