columnSuffix: dckiwrfv
contentColumnType: boolean
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: legacy
instructions: 'This page has a legacy layout available. Enable to use this layout. '
name: Legacy
searchable: false
settings:
  default: false
  offLabel: 'No'
  onLabel: 'Yes'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
