columnSuffix: null
contentColumnType: integer(10)
fieldGroup: 50e24144-f3e9-4257-8760-a53f4ff16a2a # Core
handle: monthlyAmountRaised
instructions: 'Enter the amount that has been raised so far.'
name: 'Monthly Amount Raised'
searchable: false
settings:
  decimals: 0
  defaultValue: null
  max: null
  min: '0'
  prefix: null
  previewCurrency: USD
  previewFormat: currency
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
