columnSuffix: null
contentColumnType: text
fieldGroup: 2b1d6476-49e2-48d6-a867-87f7d83ddbbc # Partners
handle: partnerColor
instructions: 'Choose a background color for this partner.'
name: 'Partner Color'
searchable: true
settings:
  allowCustomColor: false
  allowOpacity: false
  colorFormat: auto
  paletteBaseColors: null
  paletteColors: ''
  presetId: '1'
  presetMode: false
translationKeyFormat: null
translationMethod: none
type: fruitstudios\colorit\fields\ColoritField
