columnSuffix: hocrhdff
contentColumnType: text
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: partnerHeroTextHighlight
instructions: 'The highlighted and typed portion of the partner hero text. Should be in first person plural. '
name: 'Partner Hero Text Highlight'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
