columnSuffix: gnbovgrv
contentColumnType: text
fieldGroup: 2b1d6476-49e2-48d6-a867-87f7d83ddbbc # Partners
handle: partnerMotto
instructions: ''
name: 'Partner Motto'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
