columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: philosophyDescriptions
instructions: ''
name: 'Philosophy Descriptions'
searchable: false
settings:
  contentTable: '{{%matrixcontent_philosophydescriptions}}'
  maxBlocks: '3'
  minBlocks: '3'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
