columnSuffix: null
contentColumnType: text
fieldGroup: 583c55c9-886f-411a-b5eb-c6cac7f349cb # Common
handle: photoCredit
instructions: ''
name: 'Photo Credit'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
