columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: podcastTestimonials
instructions: ''
name: 'Podcast Testimonials'
searchable: false
settings:
  contentTable: '{{%matrixcontent_podcasttestimonials}}'
  maxBlocks: ''
  minBlocks: '3'
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
