columnSuffix: null
contentColumnType: text
fieldGroup: 601f52d6-827c-458a-ae29-ec5db8f8cd66 # ImageOptimize
handle: podcastArtOptimize
instructions: ''
name: 'Podcast Art Optimize'
searchable: false
settings:
  displayDominantColorPalette: '1'
  displayLazyLoadPlaceholderImages: '1'
  displayOptimizedImageVariants: '1'
  fieldVolumeSettings:
    __assoc__:
      -
        - podcast
        - '*'
  ignoreFilesOfType:
    - image/svg
    - image/gif
  variants:
    -
      __assoc__:
        -
          - width
          - '1200'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '992'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '768'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
    -
      __assoc__:
        -
          - width
          - '576'
        -
          - useAspectRatio
          - '1'
        -
          - aspectRatioX
          - '1'
        -
          - aspectRatioY
          - '1'
        -
          - retinaSizes
          -
            - '1'
            - '2'
        -
          - quality
          - '82'
        -
          - format
          - jpg
translationKeyFormat: null
translationMethod: none
type: nystudio107\imageoptimize\fields\OptimizedImages
