columnSuffix: null
contentColumnType: string
fieldGroup: 266c6678-9669-488e-82b7-68601833935a # About
handle: simpleCharityBooks
instructions: ''
name: 'Simple Charity Books'
searchable: false
settings:
  contentTable: '{{%matrixcontent_simplecharitybooks}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
