columnSuffix: null
contentColumnType: text
fieldGroup: e1f791be-0f68-4c7b-ae38-d963a110e071 # Stories
handle: storyShortTitle
instructions: 'Enter a short title to be used on the main Stories page.'
name: 'Story Short Title'
searchable: true
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: text
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
