columnSuffix: zdyvzofa
contentColumnType: text
fieldGroup: 132cb2d1-306b-49d1-8a16-ec22a6feb5a3 # Testimonials
handle: testimonialNameDescription
instructions: ''
name: 'Testimonial Name Description'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
