fieldLayouts:
  34b78039-9c59-418a-abf5-7d4e1828678c:
    tabs:
      -
        elements:
          -
            fieldUid: 7a633eca-bfc2-4150-9029-8866716a9600 # Page Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a15632d6-3fd3-4b9c-b1a5-89468da17a82 # Page Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 927a76f6-1e16-45da-998b-9795f552f597 # Light Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Data'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 4210c650-0ff5-41d2-b2c6-2581b010e6dd # Contact Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e30856e5-fcc7-42da-ae6c-514fc2d30672 # Contact Main Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Contact
        sortOrder: 2
handle: contact
hasTitleField: false
name: Contact
section: 6fa64151-393e-4fd3-a13c-5e56cdd3decf # Contact
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
