fieldLayouts:
  3841ecca-7aad-4b5a-8f9f-01a1ba205bf3:
    tabs:
      -
        elements:
          -
            fieldUid: 7a633eca-bfc2-4150-9029-8866716a9600 # Page Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a15632d6-3fd3-4b9c-b1a5-89468da17a82 # Page Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 927a76f6-1e16-45da-998b-9795f552f597 # Light Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Data'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: ''
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 9719ec4f-e8c7-42a9-9517-3e2def8c6a6b # Featured Donor Partners
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0772494f-b92f-4074-a339-65e3a912e671 # Donate Page Hero Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: dc613c25-a26c-41da-8b1f-cf6fb6f4c47a # Thank You Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Main Donater Page'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: acf0645e-0078-40b1-8fed-fe4848a4299d # Charity Bulb Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ecb7a392-a8d6-4b91-8a68-7b5a7fdd93dd # Charity Cross Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c669f297-d354-4da9-a80f-05f4e692b208 # Charity Dollar Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6d38d1b-8811-4fcf-a703-33aee65066b8 # Charity Heart Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53d39b3e-f4b6-4106-a6f2-e16a93f58998 # Charity Home Icon
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 11686273-6915-47d4-b1eb-7136d72e21e9 # Donate All Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c24063b5-7216-4828-88bc-474023b1d215 # Donate USA Map
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: cf1e109b-14f8-4ba4-ac60-4135f90aa1f9 # Charity Check
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f3ff85b-f587-4d66-8a80-7140ff5edca2 # Sample Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89f1a821-fb41-4a4b-98ce-25dd25ef6184 # Bare Caret
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 12ce8059-537f-4b8e-9577-1f16b85589b8 # Charity Caret
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: ff0ca01f-73f5-49b7-923f-c9808835ce7e # Blue Wave One
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Assets
        sortOrder: 3
handle: donate
hasTitleField: false
name: Donate
section: 6b0d2f05-4788-48d7-ba9a-6c649a489d79 # Donate
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: ''
