fieldLayouts:
  75ef2f68-0b4e-49cf-a7d8-89ebc7f1688b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: 7a633eca-bfc2-4150-9029-8866716a9600 # Page Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a15632d6-3fd3-4b9c-b1a5-89468da17a82 # Page Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 927a76f6-1e16-45da-998b-9795f552f597 # Light Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Data'
        sortOrder: 1
      -
        elements:
          -
            fieldUid: a7a14ce9-6fe8-4de9-bd97-4903128112f5 # Page Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 53b8a532-49f8-42da-81fc-58a956e8dcbe # Banner 1 Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a6c6e855-bc41-4a8d-8e0a-2c38d165b727 # Multi-Color Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 1c7830fe-aa7d-4830-a076-cef1f4188c38 # Banner 1 Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f6ff699c-9876-4f80-bb5b-8e5f493503cb # Process Hexagons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b91e077e-3da3-42ea-bb90-27c3b1ada32c # Process Hexagons Small
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 24278f74-90e5-4959-95ee-9dcdaa46e4a6 # Process Bracket 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a41134a7-7305-4eab-a699-85eeed70a2c2 # Process Bracket 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99f5768e-b360-48b6-97d7-469a83ca29e6 # Process Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Banner 1'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: dcf00203-52d9-4bda-96c9-c83dca3f13aa # Banner 2 Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f0447dfe-0355-4182-bf99-d23b289c4f6e # Process Steps
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Banner 2'
        sortOrder: 3
      -
        elements:
          -
            fieldUid: 7408fb13-95c3-469f-bf05-45f80680ab76 # Banner 3 Header
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29b81f71-d2ef-4982-9f12-708ed09a0e6f # Banner 3 Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 89ea5b4a-a42b-4b61-b234-5d3578996af3 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Banner 3'
        sortOrder: 4
      -
        elements:
          -
            fieldUid: ed9297cf-a1c1-4a43-b91d-de99dac43531 # FAQs
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: FAQs
        sortOrder: 5
      -
        elements:
          -
            fieldUid: 852293a0-2780-40b7-a388-de44cdfd2ea3 # Charity Evaluation Report
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 49ceeea8-8619-4a4c-8989-4606aa5cf8fe # Process Target 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 25581f3c-a74a-4fc1-a0a6-3a007aaac866 # Process Target 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: a4ee6689-71e0-41c4-b7c4-851661cabd19 # Process Target 3
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 4007a874-0135-4417-89e3-72c8cdd49f73 # Process Target 4
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 29a23e86-9a33-483d-a618-ebf945d1ca3f # Process Target 5
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 011489e7-5ebd-4cbd-8ecf-41512a00a694 # FAQ Caret
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Archive
        sortOrder: 6
handle: process
hasTitleField: false
name: Process
section: 414b2084-be47-492d-a203-c249c554d284 # Process
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
