fieldLayouts:
  bed03dbe-3087-4c22-9a91-032e0066de75:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: ea703e4f-5f99-4ddd-88e0-56ec3502494a # SC Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c5ae0723-b14d-4da2-b164-fcaf2bc81710 # Squiggly World Map
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: bfa3569c-ee9a-4d53-8d98-d00f60cba909 # Blue Caret
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Assets
        sortOrder: 2
handle: siteWideAssets
hasTitleField: false
name: 'Site Wide Assets'
section: f3aca6da-5684-4fb5-9035-644cbbb4f044 # Site Wide Assets
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
