fieldLayouts:
  1e50eacc-673d-4a12-b2bf-7b876b10764f:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
      -
        elements:
          -
            fieldUid: d7f7380c-11e9-4300-85f2-5160054980db # Liturgy Icons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Assets
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 8632fd0b-243b-4503-ba0b-94d375eb5951 # Simple Charity Books
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Books
        sortOrder: 3
handle: solidarity
hasTitleField: false
name: Solidarity
section: 4381d30a-d92c-4101-8a04-20a81f01ca0a # Solidarity
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
