fieldLayouts:
  9cb89040-a50d-46a4-a9d8-c5e0b16a2e74:
    tabs:
      -
        elements:
          -
            fieldUid: a15632d6-3fd3-4b9c-b1a5-89468da17a82 # Page Status
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 927a76f6-1e16-45da-998b-9795f552f597 # Light Background
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Page Data'
        sortOrder: 1
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: Title
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: bd47313e-928e-48d8-9bd4-13378649fd80 # Blog Teaser Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6597ee4f-ee31-4b87-aa82-d4c9f895e057 # Blog Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Blog Post'
        sortOrder: 2
      -
        elements:
          -
            fieldUid: 97a7725b-bca8-4548-8839-a9e841182eed # Blog Credit 
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c6a4ae52-a235-473e-86b3-9df81fc860c0 # Author Photo
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 996be234-025e-4c2f-8619-25992877c1c5 # Author Short Bio
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Author
        sortOrder: 3
handle: studentBlog
hasTitleField: true
name: 'Student Blog'
section: 16608739-7d15-4a79-bfe0-489e36e7e924 # Student Blog
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: ''
